
# Spring configuration
spring:
  application:
    name: worksync
#  jackson:
#    property-naming-strategy: SNAKE_CASE
  datasource:
#    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/worksync
    username: test
    password: king
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

# Setting request prefix
server:
  servlet:
    contextPath: /worksync

# Logging
#logging.level:
#    root: DEBUG
#    org.springframework:
#        security: TRACE
